name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v1
      
    - name: Build web-ext
      id: web-ext-build
      uses: kewisch/action-web-ext@v1.0
      with:
        cmd: build
        source: src

    - name: "Upload Artifact"
      uses: actions/upload-artifact@master
      with:
        name: schemeflooddisabler.xpi
        path: ${{ steps.web-ext-build.outputs.target }}
